version: 2.0
jobs:
  build:
    docker:
      - image: wholetale/girder:latest
      - image: mongo:3.2
    steps:
      - checkout
      - run:
          name: Installing Plugin Dependencies
          command: |
            rm -rf /girder/plugins/wt_data_manager
            ln -s /root/project /girder/plugins/wt_data_manager
            set -o pipefail; pip install --upgrade --force-reinstall -r requirements.txt | cat
      - run:
          name: Install Test Dependencies
          environment:
            - CMAKE_SHORT_VERSION: "3.4"
            - CMAKE_VERSION: "3.4.3"
            - LC_ALL: "C.UTF-8"
          command: |
            curl -OL "http://cmake.org/files/v${CMAKE_SHORT_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
            tar -x -C /usr --strip-components 1 -f "cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
            git clone https://github.com/whole-tale/girder /tmp/girder
            set -o pipefail; cd /tmp/girder ; python3 -m pip install -r requirements-dev.txt | cat
            set -o pipefail; cd /tmp/girder/pytest_girder ; python3 -m pip install . | cat
            cp /tmp/girder/CMakeLists.txt /girder/
            cp /tmp/girder/.coveragerc /girder/
            cp -r /tmp/girder/tests /girder/
            cp /root/project/setup.cfg /girder/
      - run:
          name: Running Tests
          environment:
            - PYTHON_VERSION: "3.7"
            - COVERAGE_EXECUTABLE: "/usr/local/bin/coverage"
            - FLAKE8_EXECUTABLE: "/usr/local/bin/flake8"
            - VIRTUALENV_EXECUTABLE: "/usr/local/bin/virtualenv"
            - PYTHON_EXECUTABLE: "/usr/bin/python3"
            - TEST_GROUP: "python"
          command: |
            mkdir /girder/build
            ctest -VV -S /girder/plugins/wt_data_manager/cmake/circle_continuous.cmake
      - run:
          name: Install Codecov client
          command: pip install codecov
      - run:
          name: Collect coverage reports
          command: coverage combine /girder/build/test/coverage/python_temp/
      - run:
          name: Uploading Coverage Results
          command: codecov
