name: WholeTale Data Manager
description: Implements Data Management features for the WholeTale project
version: 0.10.0.dev0
dependencies:
    - oauth
    - globus_handler
    - wholetale
    - virtual_resources
