name: WholeTale Data Manager
description: Implements Data Management features for the WholeTale project
version: 1.0rc4
dependencies:
    - oauth
    - globus_handler
    - wholetale
    - virtual_resources
